### PR TITLE
Refactored operation polling to only request active operation

### LINKED ISSUE #51: Fix for high network utilization from operation api endpoint
I recently opened a ticket for caldera, [2980](https://github.com/mitre/caldera/issues/2980) that is more closely related here. 

For reference, this is for a 5.0.0 Caldera instance running with the latest build for Magma. 

After disabling the minification for vite I was able to track down the cause. 
The calls to the API endpoint api/v2/operations were definitely coming from operationStore.js (I added a `console.error` each time it was called to be sure it was the same path. 

**vite.config.js**
```
....
  build: {
    rollupOptions: {
      external: [
        /gui/
      ]
    },
    // trbdk3 - disable minify on the output JS code since we are debugging an issue
    minify: false
  },
....
```

**operationStore.js**
```
  actions: {
    async getOperations($api) {
      try {
        console.error("Calling get v2 operations" );
        const response = await $api.get("/api/v2/operations");
        // TODO: Sort operations
        for (const operation of response.data) {
          this.operations[operation.id] = operation;
```

From here I located the calls to getOperations in `OperationsView.vue`.
The function name selectOperation lines up with non minified code. 

I'm not for sure what that code is supposed to be doing, but on the [current release](https://github.com/mitre/magma/blob/2f334cfcd54594a61102dd526f289afebc07e0f5/src/views/OperationsView.vue) there is something wrong the this logic.

**OperationsView.vue**
```
  updateInterval = setInterval(async () => {
    if (operationStore.selectedOperationID !== "") {
      await operationStore.getOperations($api);
    } else {
      clearInterval(updateInterval);
    }
  }, "3000");
```

My best guess is for some reason this is getting set to zero from the setInterval call, and the updates are running constantly. 

When I hard coded that line to what should be the fail back value it stops eating my bandwidth. 

**OperationsView.vue**
```
updateInterval = "3000" 
```

### PR DESCRIPTION
**Pull request by mkultraWasHere**
Potentially:
- addresses https://github.com/mitre/magma/pull/52
- fixes https://github.com/mitre/magma/issues/51

### CODE REVIEW

**Comment by elegantmoose** [comment]
@timbrigham-oc - Can you try this branch for me and see if it solves your problem?

i.e.
```
cd caldera/plugins/magma
git fetch --all
git checkout fix/operation_data_network_usage
cd caldera
python server.py --build
```
and let me know how it goes

**Comment by timbrigham-oc** [comment]
@elegantmoose, I just looked at this. I  do definitely see a change in behavior, it looks like it's now only pulling the specs from the currently executing operation. Very good change IMO, something I was looking at how to do myself. :)  

If I pick one of my larger lateral movement tests it's around 1.5 megabytes each pull, still much better then it has been. I am still seeing refreshes occurring on finished operations. Know that wasn't the intent of that branch, just noting its happening. 

This has dropped my network usage by an order of magnitude.

**Comment by elegantmoose** [comment]
Awesome. Ill look at the finished operations polling and see if also quick fix. Either way Ill merge this partial fix today.

**Comment by timbrigham-oc** [comment]
@elegantmoose , I'm in the middle of a test sequence now, I'll check back on this in the morning.

**Comment by elegantmoose** [comment]
@timbrigham-oc no rush 👍

**Comment by timbrigham-oc** [comment]
Ok, following up. :) 

On a preliminary look I'm still seeing operations updating on running tasks where the data refreshing only for the active operation, so that behavior still looks good. The refreshes on finished operations are also not firing, so that should be good as well.

**Comment by timbrigham-oc** [comment]
It's strange.. the same exact contents on that dialog will also show, regardless of which operation I have selected. 
If I force reload the page it clears up temporarily. 

I'm guessing it might be something along the line of whichever operation I select first - if I then select another operation - isn't getting updated.

**Comment by elegantmoose** [comment]
Yea, that was probably me that introduced those. Ill take a look at ASAP. Opened new issue - https://github.com/mitre/caldera/issues/3004

**Pull request merged**
